### ISSUE TITLE
Several Aesthetic Issues (Burners and Steam itself)

### ISSUE THREAD

**Issue by MythrilBagels** [TeamMoegMC/SteamPowered#12]
These issues aren't major, they are purely aesthetic things I've found while playing.

Issue 1: Burners don't produce light when lit.
Issue 2: When lit, Burners make way too many flame particles compared to a vanilla furnace, same with the sounds. Too frequent.
Issue 3: Steam "fluid" isn't animated.

Also, this one isn't an issue, but I wanted to ask a question, why choose Bronze, Cast Iron and Steel? Create doesn't have any of them by default and not everyone uses mods that add either of those three metals.
Thanks for your time, I'm really liking this mod :D

**Comment by khjxiaogu** [comment]
1. This require more opinion, since light may be annoying in several situations.
2. Burners are higher in power than vanilla furnace, so we just add more flames and sounds. Maybe reducing a bit is better.
3. It should be animated and not very Obvious. Take a closer look and you would find the difference.
We thought these metal looks cool compare to Vanilla or Create metals. Just imgine some gold, iron or netherite flywheel, how terrible :) And we are not going to make a copy of furnace engine. Also, this mod is originally made for modpacks, we make fallback recipe for these machines.

**Comment by MythrilBagels** [comment]
> 1. This require more opinion, since light may be annoying in several situations.
> 2. Burners are higher in power than vanilla furnace, so we just add more flames and sounds. Maybe reducing a bit is better.
> 3. It should be animated and not very Obvious. Take a closer look and you would find the difference.
>    We thought these metal looks cool compare to Vanilla or Create metals. Just imgine some gold, iron or netherite flywheel, how terrible :) And we are not going to make a copy of furnace engine. Also, this mod is originally made for modpacks, we make fallback recipe for these machines.

Thanks for responding. I want to add more.
1. I think this is ridiculous, it's a block that's visually similar to the furnace and has an open, constant burning flame. Not producing light as intentional seems like a poor design choice. I also have no idea how a burner making light would be annoying.
2. I do kind of agree with the fact that it's because it's a higher power, but at least reduce the particles. It's a lot of particles and could greatly reduce performance.
3. It may just be one of my settings, but every other liquid is animated except for steam. You say it may not be very obvious, but I watched it for a solid minute, face right against the tank and it was not animated. But I also have a suggestion for the texture of steam to vary in transparency, because steam isn't a solid colour.
I agree that Gold and Netherite wouldn't be great materials for the steam engines, but it would be nice if this mod was more standalone. Without another mod that adds these metals, the progression is really unbalanced. Tier one requires Brass, Tier two only requires Iron and Tier 3 being completely unobtainable in survival. I am currently making a Resource pack + Datapack combo that changes the three tiers to Copper, Iron and Brass.
Thanks again for your time, I hope you consider some of my feedback.

**Comment by khjxiaogu** [comment]
I looked closely at steam in Create Fluid Tanks.And I can see steam is animated. Maybe check your video settings or some display settings
