### ISSUE TITLE
[Bug/feature request] Exoflame does not power heaters

### ISSUE THREAD

**Issue by TacocaTYT** [TeamMoegMC/SteamPowered#16]
The exoflame should be be able to power the heater, or a block could be added that is enabled alongside botania being present that uses mana to make heat, a manasteel heater basically, as a side grade to the iron heater

**Comment by khjxiaogu** [comment]
Why would you think this is useful? A burner is not a furnace, using heater to heat burner has no advantage at all.

**Comment by yuesha-yc** [comment]
To clarify, the problem with this is hard to implement. We must have a same metric for fuels in both exoflames and burners.
