### ISSUE TITLE
Cogwheels turn into wood variants when encased

### ISSUE THREAD

**Issue by alexblaauw** [TeamMoegMC/SteamPowered#21]
### Error Behaviour

Steam Powered's cogwheels turn into create's regular wooden cogwheels when encased in andesite/brass casing. It's not just visual, breaking them yields a wooden cogwheel.

### Expected Behaviour

Bronze, iron and steel cogwheels should have their own encased variant blocks rather than using the default create blocks,

### Reproduce

1. Place a bronze, iron or steel cogwheel.
2. Right click while holding an andesite or brass casing

### Mod version

2.0.0-alpha

### Other mods and plugins

Create v0.4d
Flywheel v0.6.0

**Comment by yuesha-yc** [comment]
Fixes this. Now you cannot use casing on metal cogwheels. I will look at adding metal variants of encased cogwheels later.
