### ISSUE TITLE
Cogwheels can't be bracketed

### ISSUE THREAD

**Issue by alexblaauw** [TeamMoegMC/SteamPowered#22]
### Error Behaviour

In the new create version, wooden and metal brackets can be used on cogwheels to decorate them. This feature does not seem to exist for the cogwheels from Steam Powered

### Expected Behaviour

Right clicking with a wooden or metal bracket on a bronze, iron or steel cogwheel should turn the cogwheel into a bracketed version.

### Reproduce

1. Place a bronze, iron or steel cogwheel.
2. Right click while holding a bracket
3. Nothing happens

### Mod version

2.0.0-alpha

### Other mods and plugins

Create v0.4d
Flywheel v0.6.0

**Comment by yuesha-yc** [comment]
#21 See this
