### ISSUE TITLE
Burning chambers completely destroy lava buckets, meaning the bucket can't be retrieved

### ISSUE THREAD

**Issue by alexblaauw** [TeamMoegMC/SteamPowered#23]
### Error Behaviour

When inserting a lava bucket into a burning chamber via a funnel, the entire bucket gets used up, meaning that lava sources can't really be used as fuel for burning chambers. This is because the consumeFuel() function in the burner tile entity shrinks the fuel item stack regardless of what type of item it is.

### Expected Behaviour

The lava bucket should be turned into a bucket rather than being destroyed outright, allowing for the retrieval of the bucket

### Reproduce

1. Place a burning chamber in the world.
2. Place a hopper facing into it
3. Place a lava bucket in the hopper
4. Wait for the lava to be inserted into the burning chamber
5. Use /data get block [x] [y] [z] to confirm the burning chamber is empty and destroyed the bucket

### Mod version

2.0.0-alpha

### Other mods and plugins

Create v0.4d
Flywheel v0.6.0

**Comment by yuesha-yc** [comment]
Lava will be able to used in future fluid burners

**Comment by yuesha-yc** [comment]
Now it will not accept lava bucket
