### ISSUE TITLE
[Bug] Hard Limit on Steel Steam engines.

### ISSUE THREAD

**Issue by Pantheris2019** [TeamMoegMC/SteamPowered#26]
### Error Behaviour

Since this was _not_ completely solved by my previous question, I will have to report a bug for this, because I do not think this is intended.

Set up the first steel steam engine with a steel boiler/burnbox connected and pumps running at max. Worked fine.

Set up a second steel steam engine, with INDEPENDANT BOILER AND BURNBOX, same grade as the engine.  It does not pass starting and instead sits there doing nothing.

Dunno if this is an MP issue specifically or is replicated in singleplayer, but on my server, it does NOT work.

### Expected Behaviour

Each steel steam engine with associated boiler/burnbox (also steel) should start up and run smoothly.

### Reproduce

Steps listed as above.

### Mod version

1.16.5-1.1.14

### Server version

36.2.29

### Other mods and plugins

... quite a few.  But this happened BEFORE I added them.

**Comment by khjxiaogu** [comment]
You should have totally independent system. WHICH MEANS PUMPS AND PIPES "MUST" BE INDEPENDENT.
