### ISSUE TITLE
[Bug] Dangerous Alternative Prefix

### ISSUE THREAD

**Issue by itsdinkd** [TeamMoegMC/SteamPowered#27]
### Error Behaviour

In console, servers/single player logs are getting spammed about a message on alternative dangerous prefix. see log

### Expected Behaviour

not spammed

### Reproduce

1. launch game
2. join world
3. check logs

### Crash Report

https://gist.github.com/itsdinkd/b5959aa269d1d6ce4786d582b545422d

### Mod version

2.0.0-alpha

### Server version

1.18.1

**Comment by yuesha-yc** [comment]
I don't think this affects in-game.

**Comment by itsdinkd** [comment]
No it doesn't affect the game but it spams logs and also creates unnecessary SSD writes for players.

**Comment by wilyank** [comment]
The log says that this dangerous alternative prefix can mean two things: an intentional override, or a broken mod.
Are you intentionally overriding every item and block in the Create mod, or is your mod broken?
