### ISSUE TITLE
[Bug] Mekanism Steel doesn't seem to be valid for Boilers, Burning Chambers, Large Cog Wheels, and Engines

### ISSUE THREAD

**Issue by NullMagic** [TeamMoegMC/SteamPowered#29]
### Error Behaviour

Steel Boiler, Burning Chamber, Large Cog Wheel, and Engine are not available with both Steam Powered and Mekanism installed.

### Expected Behaviour

With Steam Powered and Mekanism installed one would expect that Mekanism Steel could be used to make Steam Powered machines

### Reproduce

1. Install Steam Power
2. Install Mekanism
3. Attempt to make a steam boiler

### Mod version

1.16.5-1.1.14

**Comment by yuesha-yc** [comment]
<img width="1136" alt="Screen Shot 2022-03-26 at 8 43 51 PM" src="https://user-images.githubusercontent.com/52098789/160265711-98a12f3b-a35f-4fa7-a779-4ff93d9ba55c.png">
Seems to work with me.

**Comment by yuesha-yc** [comment]
Boilers require Steel Plate. You should install Create: Alloyed to get it. https://www.curseforge.com/minecraft/mc-mods/create-alloyed
