### ISSUE TITLE
[Bug] You require a mod version that does not exist.

### ISSUE THREAD

**Issue by MagmaBro123** [TeamMoegMC/SteamPowered#30]
### Error Behaviour

Title. You require a mod version between 0.6.0, and 0.6.1, which does not exist. The error below clearly states this.

![2022-03-14_18 42 04](https://user-images.githubusercontent.com/51277766/158289318-aa0806a6-8251-4a99-9e73-d4126317ad6c.png)

### Expected Behaviour

The game to load.

### Reproduce

Install this mod along with its required mods like usual.

### Crash Report

https://pastebin.com/qBnULLR8

### Mod version

2.0.0 Alpha 2.

### Other mods and plugins

None.

**Comment by wolflord212312** [comment]
https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3623314

**Comment by wolflord212312** [comment]
we are curently waiting on support for the new update
you will also need to downgrade create too 
 [Create 1.18.1 v0.4d ](https://www.curseforge.com/minecraft/mc-mods/create/files/3623348)

**Comment by MagmaBro123** [comment]
I am using 0.6.0.

**Comment by NovaLynxie** [comment]
I'm glad I am not the only one having this issue. This is causing serious problems when updating or downgrading Create and its addons. Please can this be fixed and use a version that actually exists.
Also side note, 0.6.1 is actually version 0.6.1.63 according to forge which does not satisfy the <0.6.0 and >0.6.1 requirement.

**Comment by MagmaBro123** [comment]
0.6.1.63 doesn't exist.

**Comment by MagmaBro123** [comment]
What version do I need then. Both 0.6.0 and 0.6.1 don't work.

**Comment by Panderine** [comment]
flywheel version 0.6.0 will work, but you cannot use latest Create with that version. So you would need to downgrade Create as well as flywheel

**Comment by MagmaBro123** [comment]
You said use flywheel 0.6.0 but downgrade it too. Now I'm more confused.
