### ISSUE TITLE
[Bug] doesnt work with never flywheel versions

### ISSUE THREAD

**Issue by ZEROX7** [TeamMoegMC/SteamPowered#32]
### Error Behaviour

![javaw_E0JhOQnSBr](https://user-images.githubusercontent.com/12628051/159999801-2d8be8a1-cc3d-48e9-8448-bb95aaf165c8.png)

### Expected Behaviour

never create needs flywheel 0.6.1 wich your mod doesnt support

### Reproduce

install nevest version of create and flywheel

### Mod version

steampowered-1.18.1-2.0.0-alpha-2.jar

**Comment by XenoxUSser** [comment]
the bug is still happeneing with newest version :/
