### ISSUE TITLE
[Suggestion] Support for 1.18.2

### ISSUE THREAD

**Issue by isaaclepes** [TeamMoegMC/SteamPowered#33]
### Suggestion

Support for 1.18.2

### Reason

It seems like the next logical update to make and many people would be interested in using this mod with the latest version of Minecraft.

### Exsiting Mods

Not that I am aware of.  You did good work here, I doubt another mod could replace it.

I do see it listed in Pull requests, but I receive a mod failed to load error when trying it on 1.18.2.
https://github.com/TeamMoegMC/SteamPowered/pull/31

**Comment by xuwuwudi** [comment]
1182！（）

**Comment by yuyijun12** [comment]
i need1.18.2，so that 1.18.1 is so unstable
