### ISSUE TITLE
[Bug] 1.18.2 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by T-Jeremy** [TeamMoegMC/SteamPowered#34]
### Error Behaviour

![image](https://user-images.githubusercontent.com/14940407/163997208-329d528e-469c-4b2d-8f2a-fb45b93b3867.png)

### Expected Behaviour

To load the game properly

### Reproduce

- Install jdk-17.0.2
- Install Minecraft version 1.18.2
- Install Forge version 1.18.2-forge-40.1.0
- Install createaddition-1.18.2-20220417a
- Install flywheel-forge-1.18-0.6.2
- (+ a bunch of other mods)

### Crash Report

https://pastebin.com/vVtssXc5

### Mod version

20220417a

### Other mods and plugins

We can see other mods on the pastebin

**Comment by KintsugiKitten** [comment]
How was this solved? I am having the same problem, and what's more is that it causes Create to have the same error. I know it's because of Steam Powered because launching without it does not cause the crash. Forge version is 40.1.55, Create is 0.5.0, and Flywheel is 0.6.3.
