### ISSUE TITLE
Balance: Steam Engines are way too underpowered compared to Furnace engines

### ISSUE THREAD

**Issue by Lgmrszd** [TeamMoegMC/SteamPowered#6]
Steam Engines, while being somewhat easier to maintain, provide output way too low (3072 su on 32 RPM on Steel Steam Engine, compared to 16384 su on 16 rpm with Furnace Engine on simple furnace). There is no practical point of using these engines from players perspective.

**Comment by khjxiaogu** [comment]
This mod is for modpacks at the beginning, which means, modpack author may disable or weaken Furnace Engine to make Steam Engines more practical.

**Comment by khjxiaogu** [comment]
However, you can edit config to rebalance Steam Engines' output as you like.
