### ISSUE TITLE
Cogwheel impact not working

### ISSUE THREAD

**Issue by Voryson** [TeamMoegMC/SteamPowered#8]
Hey, 

Thanks for the mod!

I did input a 
castIronCogwheelImpact = 0.05
bronzeCogwheelImpact = 0.025
in the config file, but there is no impact in game after restarting :(
I did put cogwheel impact on the basic wooden cogwheel in the Create config, with decimal values as well, and it works like a charm.

A lil help would be great!
Thanks

**Comment by khjxiaogu** [comment]
Cannot reproduce, can you post your full config file?
