### ISSUE TITLE
Bad tags

### ISSUE THREAD

**Issue by Hexidecimark** [TeamMoegMC/SteamPowered#9]
MC 1.16.5
Forge 36.2.4
Steampowered 1.1.7c
Pack list: https://www.curseforge.com/minecraft/modpacks/hexworks/relations/dependencies

Forge returns parsing errors on the steel steam engine, steel boilers, and steel burners because you do not register steel plates. It returns parsing errors on steel flywheels, steel cogwheels, and large steel cogwheels because you do not register steel ingots.

**Comment by khjxiaogu** [comment]
Our mod does not provide steel item now, you may need to modify the recipe or install a mod with steel.

**Comment by Hexidecimark** [comment]
Is the provision of steel creation through create something planned here or elsewhere? I suppose I can also just configure everything a tier up.

**Comment by khjxiaogu** [comment]
Steel is provided by other mods like IE or whatever. Since a lot of mods provide steel, modpack authors can define their own steel, we may not add steel.

**Comment by SteamDoge9000** [comment]
It might not be a bad idea to have it not register if no steel tag is present, or do what I saw in the Capsules mod (item still register, but something else takes its place to indicate its uncreatable and that a missing tag is present

**Comment by khjxiaogu** [comment]
We found that a new mod called Create:Alloyed add all these material, and we may put it in our recommended dependency. This issue is consider resolved.

**Comment by ChiefArug** [comment]
Can I ask that you add a condition to your recipe json to prevent the recipe from trying to load if the steel items do not exist?
It is very annoying when reading logs but having them full of stacktraces just because a mod doesn't use recipe conditions.
It is just this: 
```json
"conditions": [
    {
      "type": "forge:not",
      "value": {
        "tag": "forge:ingots/steel",
        "type": "forge:tag_empty"
      }
    }
]
``` 
Where `forge:ingots/steel` is the tag it checks for.
And here is an example of Create themselves using it: https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/generated/resources/data/create/recipes/crushing/raw_platinum_ore.json

**Comment by khjxiaogu** [comment]
> Can I ask that you add a condition to your recipe json to prevent the recipe from trying to load if the steel items do not exist? It is very annoying when reading logs but having them full of stacktraces just because a mod doesn't use recipe conditions. It is just this:
> 
> ```json
> "conditions": [
>     {
>       "type": "forge:not",
>       "value": {
>         "tag": "forge:ingots/steel",
>         "type": "forge:tag_empty"
>       }
>     }
> ]
> ```
> 
> Where `forge:ingots/steel` is the tag it checks for. And here is an example of Create themselves using it: https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/generated/resources/data/create/recipes/crushing/raw_platinum_ore.json

I can add this, but what for? And I think this would be a notice that you didn't add any steel in your game. If you want to dismiss this stacktrace, just remove the recipe with datapack or something similiar.

**Comment by ChiefArug** [comment]
> I can add this, but what for?

Cleaning up the logs, its not nice when they are clogged with easily preventable errors (note its one stacktrace per recipe, not per tag/item)
> If you want to dismiss this stacktrace, just remove the recipe with datapack

I'm aware you can do that, but I help people in a discord server by reading logs and crash logs for them, and its not practical to tell them to add a datapack just to clean up the log, especially when its so easily preventable on the mods end.
